### ISSUE TITLE
Can't run behat

### ISSUE THREAD

**Issue by TamerQtaish** [arisro/behat-lumen-extension#3]
I can't seem to be able to run behat; I keep getting this Exception:
`[ErrorException]                                                                                                                                                                          
  Argument 1 passed to Arisro\Behat\Driver\LumenDriver::__construct() must be an instance of Symfony\Component\HttpKernel\HttpKernelInterface, instance of Laravel\Lumen\Application given`

My composer.json files is straight forward:
`{
    "name": "laravel/lumen",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "5.2.*",
        "vlucas/phpdotenv": "~2.2"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~4.0",
        "behat/behat": "~3.0",
        "behat/mink": "~1.6",
        "behat/mink-extension": "~2.1",
        "arisro/behat-lumen-extension": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/",
            "database/"
        ]
    }
}
`

Any help will be appreciated

**Comment by arisro** [comment]
Hey @TamerQtaish,

1.\* is not compatible with Lumen 5.2+ (#2).
Please use v2.0.0 of the package; consider using ^2.0 in your composer.json because I will push some more fixes to v2 soonish.

Cheers,
Aris
